/*
 * Generates src/content/terms.ts from the monorepo's legal text
 * (../docs/DISCLAIMER_TERMS_v<version>_{EN,IT}.md), so the dApp serves the
 * SAME words the repository publishes. Re-run after every change to the terms:
 *   npm run terms
 * A new version also means bumping TERMS_VERSION below: every visitor is then
 * asked to accept again (src/components/TermsGate.tsx).
 *
 * Only the markdown subset those two files use is understood: "# " / "## "
 * headings, paragraphs, "- " lists (with indented continuation lines), "> "
 * quotes, "---" rules, **bold** and *italic*. Anything else fails loudly.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const TERMS_VERSION = "0.2";

const root = dirname(fileURLToPath(import.meta.url));
const docsDir = join(root, "..", "..", "docs");
const outFile = join(root, "..", "src", "content", "terms.ts");

/** "a **b** *c*" -> [{text:"a "},{text:"b",b:true},{text:" "},{text:"c",i:true}] */
function inline(text) {
  const out = [];
  const re = /\*\*(.+?)\*\*|\*(.+?)\*/g;
  let last = 0;
  let m;
  while ((m = re.exec(text))) {
    if (m.index > last) out.push({ text: text.slice(last, m.index) });
    out.push(m[1] !== undefined ? { text: m[1], b: true } : { text: m[2], i: true });
    last = re.lastIndex;
  }
  if (last < text.length) out.push({ text: text.slice(last) });
  if (out.some((r) => r.text.includes("*"))) throw new Error(`unbalanced emphasis: ${text}`);
  return out;
}

function parse(md) {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  const blocks = [];
  let para = null; // { kind: "p" | "quote", lines: [] }
  let list = null; // string[][]

  function flush() {
    if (para) blocks.push({ type: para.kind, text: inline(para.lines.join(" ")) });
    if (list) blocks.push({ type: "ul", items: list.map((l) => inline(l.join(" "))) });
    para = null;
    list = null;
  }

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (line === "") {
      flush();
    } else if (line === "---") {
      flush();
      blocks.push({ type: "hr" });
    } else if (line.startsWith("## ")) {
      flush();
      blocks.push({ type: "h2", text: inline(line.slice(3)) });
    } else if (line.startsWith("# ")) {
      flush();
      blocks.push({ type: "h1", text: inline(line.slice(2)) });
    } else if (line.startsWith("- ")) {
      if (para) flush();
      list ??= [];
      list.push([line.slice(2)]);
    } else if (list && /^\s+\S/.test(line)) {
      list[list.length - 1].push(line.trim());
    } else if (line.startsWith("> ") || line === ">") {
      if (para && para.kind !== "quote") flush();
      if (list) flush();
      para ??= { kind: "quote", lines: [] };
      para.lines.push(line.slice(2));
    } else if (/^[#>|`]/.test(line)) {
      throw new Error(`unsupported markdown: ${line}`);
    } else {
      if (list) flush();
      if (para && para.kind !== "p") flush();
      para ??= { kind: "p", lines: [] };
      para.lines.push(line.trim());
    }
  }
  flush();
  return blocks;
}

const terms = {};
for (const lang of ["en", "it"]) {
  const file = `DISCLAIMER_TERMS_v${TERMS_VERSION}_${lang.toUpperCase()}.md`;
  terms[lang] = { source: `docs/${file}`, blocks: parse(readFileSync(join(docsDir, file), "utf8")) };
  console.log(`OK ${file} (${terms[lang].blocks.length} blocks)`);
}

const body =
  `// GENERATED by scripts/generate-terms.mjs — do not edit by hand.\n` +
  `// Source: docs/DISCLAIMER_TERMS_v${TERMS_VERSION}_{EN,IT}.md\n` +
  `export type TermsRun = { text: string; b?: boolean; i?: boolean };\n` +
  `export type TermsBlock =\n` +
  `  | { type: "h1" | "h2" | "p" | "quote"; text: TermsRun[] }\n` +
  `  | { type: "ul"; items: TermsRun[][] }\n` +
  `  | { type: "hr" };\n\n` +
  `export const TERMS_VERSION = ${JSON.stringify(TERMS_VERSION)};\n\n` +
  `export const TERMS: Record<"en" | "it", { source: string; blocks: TermsBlock[] }> = ${JSON.stringify(terms, null, 2)};\n`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, body);
