// GENERATED by scripts/generate-terms.mjs — do not edit by hand.
// Source: docs/DISCLAIMER_TERMS_v0.3_{EN,IT}.md
export type TermsRun = { text: string; b?: boolean; i?: boolean };
export type TermsBlock =
  | { type: "h1" | "h2" | "p" | "quote"; text: TermsRun[] }
  | { type: "ul"; items: TermsRun[][] }
  | { type: "hr" };

export const TERMS_VERSION = "0.3";

/*
 * Acceptance marker read before paint (src/components/TermsGate.tsx). This
 * module has no "use client": the layout inlines TERMS_ACCEPTED_SCRIPT in
 * <head>, and a value imported from a client module would reach the RSC
 * payload as a client reference instead of the literal string (React
 * replays the suspended <head>, intermittent #418 on fresh loads).
 */
export const TERMS_STORAGE_KEY = "daimon-terms";
export const TERMS_ACCEPTED_ATTR = "data-terms-accepted";

export const TERMS_ACCEPTED_SCRIPT = `
try {
  var a = JSON.parse(localStorage.getItem('${TERMS_STORAGE_KEY}') || 'null');
  if (a && a.version === '${TERMS_VERSION}') document.documentElement.setAttribute('${TERMS_ACCEPTED_ATTR}', '');
} catch (e) {}
`;

export const TERMS: Record<"en" | "it", { source: string; blocks: TermsBlock[] }> = {
  "en": {
    "source": "docs/DISCLAIMER_TERMS_v0.3_EN.md",
    "blocks": [
      {
        "type": "h1",
        "text": [
          {
            "text": "Daimon — Legal Disclaimer & Terms of Use"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "v0.3 — 29 September 2026. Placement: website (footer link + dedicated page); dApp entry (acknowledgment required before first interaction, including the user's responsibility for lawful use per §5); repository README (short form linking to the full text). The English text is the only authoritative version (§8).",
            "i": true
          }
        ]
      },
      {
        "type": "hr"
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "1. Nature of the software"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Daimon is experimental, open-source software: a set of immutable smart contracts deployed on a public blockchain. It is provided "
          },
          {
            "text": "\"as is\" and \"as available\"",
            "b": true
          },
          {
            "text": ", without warranties of any kind, express or implied — including but not limited to merchantability, fitness for a particular purpose, or non-infringement."
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "The contributors who wrote and published this code do not operate, control, custody, or intermediate anything. Once deployed, the contracts run autonomously; no person or entity can modify them outside the on-chain governance rules encoded in the contracts themselves. There is no company, foundation, or issuer behind this software."
          }
        ]
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "2. No offer, no solicitation, no advice"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Nothing published by the Daimon contributors — code, documentation, protocol paper, website, or social channels — constitutes an offer to sell, a solicitation to buy, or a recommendation of any token, security, financial instrument, or investment strategy, in any jurisdiction. Nothing constitutes financial, legal, accounting, or tax advice. Consult your own qualified advisors."
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "The DMN token is not sold by anyone. It confers no claim, right, dividend, or expectation of profit against any person or entity. The migration from the predecessor token is voluntary, free of charge, and 1:1; no funds are raised from anyone at any time."
          }
        ]
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "3. Forward-looking statements and continued development"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Any statement about future development — directions, ideas, possible modules, or the shape of what may come after mainnet — describes intent at the time of writing. Such statements are aspirational, not commitments, promises, or offers. Direction can change, be delayed, or be abandoned, and any change to the protocol itself can occur only through its public, time-delayed on-chain governance."
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "The contributors have no obligation to continue developing, maintaining, promoting, or supporting the software, and may reduce or cease their involvement at any time. The contracts do not depend on any person's continued participation to keep operating."
          }
        ]
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "4. You interact at your own risk"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "By interacting with the contracts you acknowledge that:"
          }
        ]
      },
      {
        "type": "ul",
        "items": [
          [
            {
              "text": "you interact "
            },
            {
              "text": "directly with a public blockchain",
              "b": true
            },
            {
              "text": ", with no intermediary, no custodian, and no counterparty;"
            }
          ],
          [
            {
              "text": "smart contracts can contain defects. An independent security audit has been performed and published in full; an audit reduces risk, it does not eliminate it;"
            }
          ],
          [
            {
              "text": "digital assets are volatile and can lose all value; transactions are irreversible; loss of keys means loss of assets;"
            }
          ],
          [
            {
              "text": "on-chain governance can change the parameters that the code allows it to change, through public proposals and time delays;"
            }
          ],
          [
            {
              "text": "the regulatory treatment of digital assets varies by jurisdiction and can change; you are solely responsible for determining whether your use of the software is lawful where you live."
            }
          ]
        ]
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "5. Lawful use"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "The software and any related interface are not directed at, and must not be used by: persons in jurisdictions where such use is prohibited; persons subject to sanctions administered by the UN, EU, US (OFAC), UK, or equivalent authorities; or any person for whom access would impose licensing, registration, or prospectus obligations on any party. If you fall into any of these categories, do not interact with the contracts or interfaces."
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "The smart contracts are permissionless by design, and the interfaces published by the contributors do not restrict access by location. Each user is solely responsible for complying with the laws and regulations that apply to them, and must not use the software or any interface where doing so is prohibited."
          }
        ]
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "6. Limitation of liability"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "To the maximum extent permitted by applicable law, the contributors shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages — including loss of funds, data, or profits — arising from or related to the software, its use, or the inability to use it, under any theory of liability, even if advised of the possibility of such damages."
          }
        ]
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "7. Verifiability"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "The source code, the audit report, and all project documentation are public. "
          },
          {
            "text": "Do not trust these statements — verify them against the code.",
            "b": true
          },
          {
            "text": " Where this text and the deployed code disagree, the code is the only authority."
          }
        ]
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "8. Language"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "This document is written in English. Translations may be provided for convenience only; in case of any divergence, the English version prevails."
          }
        ]
      },
      {
        "type": "hr"
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Short form (repository README / dApp footer):",
            "i": true
          }
        ]
      },
      {
        "type": "quote",
        "text": [
          {
            "text": "Daimon is experimental open-source software provided \"as is\", without warranties. Nothing here is an offer, solicitation, or financial advice; statements about future development are intent, not promises. No entity operates the protocol and no one is obliged to maintain it; you interact directly with immutable smart contracts on a public blockchain, at your own risk. Digital assets can lose all value. Use of the software may be restricted in your jurisdiction — you are solely responsible for compliance with your local laws. Where this text and the deployed code disagree, the code is the only authority."
          }
        ]
      },
      {
        "type": "hr"
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Changelog — v0.3 (29 September 2026): §5 now states that the interfaces do not restrict access by location and that each user is responsible for lawful use where they are; the header now refers to §5 (it cited §4 by mistake).",
            "i": true
          }
        ]
      }
    ]
  },
  "it": {
    "source": "docs/DISCLAIMER_TERMS_v0.3_IT.md",
    "blocks": [
      {
        "type": "h1",
        "text": [
          {
            "text": "Daimon — Avvertenze legali e Condizioni d'uso"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "v0.3 — 29 settembre 2026. Traduzione di cortesia: fa fede esclusivamente il testo inglese (§8).",
            "i": true
          }
        ]
      },
      {
        "type": "hr"
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "1. Natura del software"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Daimon è software sperimentale e open source: un insieme di smart contract immutabili distribuiti su una blockchain pubblica. È fornito "
          },
          {
            "text": "\"così com'è\" e \"secondo disponibilità\"",
            "b": true
          },
          {
            "text": ", senza garanzie di alcun tipo, espresse o implicite — incluse, a titolo non esaustivo, quelle di commerciabilità, idoneità a uno scopo specifico o non violazione di diritti altrui."
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "I contributori che hanno scritto e pubblicato questo codice non gestiscono, controllano, custodiscono né intermediano alcunché. Una volta distribuiti, i contratti operano autonomamente; nessuna persona o entità può modificarli al di fuori delle regole di governance on-chain codificate nei contratti stessi. Non esiste alcuna società, fondazione o emittente dietro questo software."
          }
        ]
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "2. Nessuna offerta, nessuna sollecitazione, nessuna consulenza"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Nulla di quanto pubblicato dai contributori di Daimon — codice, documentazione, protocol paper, sito web o canali social — costituisce un'offerta di vendita, una sollecitazione all'acquisto o una raccomandazione di alcun token, strumento finanziario, valore mobiliare o strategia d'investimento, in alcuna giurisdizione. Nulla costituisce consulenza finanziaria, legale, contabile o fiscale. Consultate i vostri consulenti qualificati."
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Il token DMN non viene venduto da nessuno. Non conferisce alcun credito, diritto, dividendo o aspettativa di profitto nei confronti di alcuna persona o entità. La migrazione dal token precedente è volontaria, gratuita e 1:1; nessun fondo viene raccolto da nessuno, in nessun momento."
          }
        ]
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "3. Dichiarazioni prospettiche e continuità dello sviluppo"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Qualsiasi affermazione sullo sviluppo futuro — direzioni, idee, possibili moduli, o la forma di ciò che potrà venire dopo il mainnet — descrive un'intenzione al momento in cui è scritta. Tali affermazioni sono aspirazioni, non impegni, promesse o offerte. La direzione può cambiare, subire ritardi o essere abbandonata, e qualsiasi modifica al protocollo può avvenire soltanto attraverso la sua governance on-chain, pubblica e soggetta a ritardo temporale."
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "I contributori non hanno alcun obbligo di continuare a sviluppare, mantenere, promuovere o supportare il software, e possono ridurre o cessare il proprio coinvolgimento in qualsiasi momento. I contratti non dipendono dalla partecipazione continuativa di alcuna persona per continuare a funzionare."
          }
        ]
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "4. Interagite a vostro rischio"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Interagendo con i contratti riconoscete che:"
          }
        ]
      },
      {
        "type": "ul",
        "items": [
          [
            {
              "text": "interagite "
            },
            {
              "text": "direttamente con una blockchain pubblica",
              "b": true
            },
            {
              "text": ", senza intermediari, senza custodi e senza controparti;"
            }
          ],
          [
            {
              "text": "gli smart contract possono contenere difetti. È stato eseguito e pubblicato integralmente un audit di sicurezza indipendente; un audit riduce il rischio, non lo elimina;"
            }
          ],
          [
            {
              "text": "gli asset digitali sono volatili e possono perdere tutto il loro valore; le transazioni sono irreversibili; la perdita delle chiavi comporta la perdita degli asset;"
            }
          ],
          [
            {
              "text": "la governance on-chain può modificare i parametri che il codice le consente di modificare, attraverso proposte pubbliche e ritardi temporali;"
            }
          ],
          [
            {
              "text": "il trattamento normativo degli asset digitali varia da giurisdizione a giurisdizione e può cambiare; siete gli unici responsabili di stabilire se l'uso del software è lecito nel luogo in cui vivete."
            }
          ]
        ]
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "5. Uso lecito"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Il software e qualsiasi interfaccia correlata non sono destinati a, e non devono essere utilizzati da: persone che si trovano in giurisdizioni in cui tale uso è vietato; persone soggette a sanzioni amministrate da ONU, UE, USA (OFAC), Regno Unito o autorità equivalenti; o qualsiasi persona per la quale l'accesso comporterebbe obblighi di licenza, registrazione o prospetto a carico di chiunque. Se rientrate in una di queste categorie, non interagite con i contratti né con le interfacce."
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Gli smart contract sono per costruzione privi di permessi, e le interfacce pubblicate dai contributori non limitano l'accesso in base alla posizione. Ciascun utente è l'unico responsabile del rispetto delle leggi e dei regolamenti che gli si applicano, e non deve usare il software né alcuna interfaccia dove ciò è vietato."
          }
        ]
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "6. Limitazione di responsabilità"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Nella misura massima consentita dalla legge applicabile, i contributori non saranno responsabili per alcun danno diretto, indiretto, incidentale, speciale, consequenziale o esemplare — inclusa la perdita di fondi, dati o profitti — derivante da o correlato al software, al suo uso o all'impossibilità di usarlo, secondo qualsiasi teoria di responsabilità, anche se avvisati della possibilità di tali danni."
          }
        ]
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "7. Verificabilità"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Il codice sorgente, il report dell'audit e tutta la documentazione del progetto sono pubblici. "
          },
          {
            "text": "Non fidatevi di queste affermazioni — verificatele contro il codice.",
            "b": true
          },
          {
            "text": " Dove questo testo e il codice distribuito non concordano, l'unica autorità è il codice."
          }
        ]
      },
      {
        "type": "h2",
        "text": [
          {
            "text": "8. Lingua"
          }
        ]
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Il presente documento è redatto in inglese. Le traduzioni sono fornite unicamente per comodità; in caso di divergenza prevale la versione inglese."
          }
        ]
      },
      {
        "type": "hr"
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Forma breve (README del repository / piè di pagina della dApp):",
            "i": true
          }
        ]
      },
      {
        "type": "quote",
        "text": [
          {
            "text": "Daimon è software sperimentale open source fornito \"così com'è\", senza garanzie. Nulla qui è un'offerta, una sollecitazione o una consulenza finanziaria; le affermazioni sullo sviluppo futuro sono intenzioni, non promesse. Nessuna entità gestisce il protocollo e nessuno è obbligato a mantenerlo; interagite direttamente con smart contract immutabili su una blockchain pubblica, a vostro rischio. Gli asset digitali possono perdere tutto il loro valore. L'uso del software può essere soggetto a restrizioni nella vostra giurisdizione — siete gli unici responsabili del rispetto delle leggi locali. Dove questo testo e il codice distribuito non concordano, l'unica autorità è il codice."
          }
        ]
      },
      {
        "type": "hr"
      },
      {
        "type": "p",
        "text": [
          {
            "text": "Modifiche — v0.3 (29 settembre 2026): il §5 ora afferma che le interfacce non limitano l'accesso in base alla posizione e che ciascun utente è responsabile di un uso lecito nel luogo in cui si trova; l'intestazione del testo inglese ora rimanda al §5 (citava per errore il §4).",
            "i": true
          }
        ]
      }
    ]
  }
};
